### ISSUE TITLE
Don't allow conflicting card packs

### ISSUE THREAD

**Issue by grifferz** [grifferz/pah-irc#138]
Now that we have some card packs that are mutually exclusive (cah_us conflicts with cah_uk, cah_us_uk conflicts with cah_us) there should perhaps be some way for the pack maintainer to specify this, to prevent accidents.

We could add a Conflicts header:

``` yaml
Description:    Cards Against Humanity (US \ UK)
Conflicts:
    - cah_us (Already contains US cards)
```

And then refuse to load any deck that contained conflicts, before messing with the database.
